#!/usr/bin/env python3
"""
Emit a bash script that runs profile/batch_profile.py for multiple method / hispec combinations.

Includes **vanila + --hispec** (with --interval >= 1) alongside baseline vanila and other modes.
Use distinct --output-dir roots per job so vanila and vanila+hispec do not share the same
method__vanila output tree.
"""

from __future__ import annotations

import argparse
from pathlib import Path


def _shell_quote(s: str) -> str:
    return "'" + s.replace("'", "'\"'\"'") + "'"


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generate a shell script for batch_profile.py runs.")
    p.add_argument(
        "--out-sh",
        type=str,
        default="profile/run_batch_profile_jobs.sh",
        help="Path to the generated .sh file (relative to repo root or absolute).",
    )
    p.add_argument(
        "--data-dir",
        type=str,
        default="",
        help="Passed through to batch_profile --data-dir. Default: use $SSD_DATASET_DIR at shell runtime (must be set).",
    )
    p.add_argument(
        "--output-dir-root",
        type=str,
        default="profile/results_batch",
        help="Base directory; each job uses a job-specific subdirectory under this root.",
    )
    p.add_argument(
        "--datasets",
        type=str,
        default="alpaca,gsm8k,humaneval,mt_bench,qa",
        help="Comma-separated dataset keys for batch_profile.",
    )
    p.add_argument("--k", type=int, default=5)
    p.add_argument("--batch-size", type=int, default=4)
    p.add_argument(
        "--hispec-intervals",
        type=str,
        default="4",
        help="Comma-separated interval values for vanila+hispec and topk_expansion+hispec jobs.",
    )
    p.add_argument(
        "--topk-selection",
        type=int,
        default=5,
        choices=[2, 5],
    )
    p.add_argument("--expansion-pct", type=float, default=0.2)
    p.add_argument(
        "--include",
        type=str,
        default="vanila,vanila_hispec,topk_expansion,topk_expansion_hispec,bump,morphable",
        help="Comma-separated job kinds to emit (see script header for names).",
    )
    return p.parse_args()


def main() -> int:
    args = parse_args()
    out_path = Path(args.out_sh).expanduser()
    if not out_path.is_absolute():
        repo_root = Path(__file__).resolve().parents[1]
        out_path = (repo_root / out_path).resolve()

    intervals = [int(x.strip()) for x in args.hispec_intervals.split(",") if x.strip()]
    for iv in intervals:
        if iv < 1:
            raise ValueError(f"--hispec-intervals values must be >= 1, got {iv}")

    include = {x.strip() for x in args.include.split(",") if x.strip()}

    out_root = args.output_dir_root.rstrip("/")

    lines: list[str] = [
        "#!/usr/bin/env bash",
        "# Generated by profile/gen_batch_script.py — edit job list or re-run generator as needed.",
        "set -euo pipefail",
        "",
        'REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"',
        'cd "$REPO_ROOT"',
        "",
        'PYTHON="${PYTHON:-python}"',
        'BATCH_PROFILE="$REPO_ROOT/profile/batch_profile.py"',
        "",
    ]
    if args.data_dir:
        lines.append(f'DATA_DIR={_shell_quote(args.data_dir)}')
    else:
        lines.extend(
            [
                ': "${SSD_DATASET_DIR:?Set SSD_DATASET_DIR to your dataset root (or pass --data-dir to gen_batch_script.py).}"',
                'DATA_DIR="$SSD_DATASET_DIR"',
            ]
        )
    lines.extend(
        [
        f'DATASETS={_shell_quote(args.datasets)}',
        f'OUT_ROOT={_shell_quote(out_root)}',
        f'K={args.k}',
        f'BATCH_SIZE={args.batch_size}',
        f'TOPK_SEL={args.topk_selection}',
        f'EXP_PCT={args.expansion_pct}',
        "",
        ]
    )
    lines.extend(
        [
        "_run() {",
        '  local name="$1"',
        "  shift",
        '  echo "=== ${name} ==="',
        '  "$PYTHON" "$BATCH_PROFILE" \\',
        '    --data-dir "$DATA_DIR" \\',
        '    --datasets "$DATASETS" \\',
        '    --output-dir "$OUT_ROOT/$name" \\',
        '    --k "$K" \\',
        '    --batch-size "$BATCH_SIZE" \\',
        '    "$@"',
        "}",
        "",
        ]
    )

    if "vanila" in include:
        lines.extend(
            [
                '# Baseline vanila (no hispec)',
                '_run vanila_plain --method vanila',
                "",
            ]
        )

    if "vanila_hispec" in include:
        for iv in intervals:
            suffix = f"vanila_hispec_interval{iv}"
            lines.extend(
                [
                    f"# Vanila + hispec (intermediate rounds + target commit every {iv} verifier steps)",
                    f'_run {suffix} --method vanila --hispec --interval {iv}',
                    "",
                ]
            )

    if "topk_expansion" in include:
        lines.extend(
            [
                "_run topk_expansion \\",
                f"  --method topk_expansion --topk-selection $TOPK_SEL --expansion-pct $EXP_PCT",
                "",
            ]
        )

    if "topk_expansion_hispec" in include:
        for iv in intervals:
            suffix = f"topk_expansion_hispec_interval{iv}"
            lines.extend(
                [
                    f"_run {suffix} \\",
                    "  --method topk_expansion --hispec \\",
                    f"  --interval {iv} --topk-selection $TOPK_SEL --expansion-pct $EXP_PCT",
                    "",
                ]
            )

    if "bump" in include:
        lines.extend(
            [
                "_run bump --method bump",
                "",
            ]
        )

    if "morphable" in include:
        lines.extend(
            [
                "_run morphable --method morphable",
                "",
            ]
        )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(lines) + "\n"
    out_path.write_text(text, encoding="utf-8")
    out_path.chmod(out_path.stat().st_mode | 0o111)
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
