#!/usr/bin/env bash
# Generated by profile/gen_batch_script.py — edit job list or re-run generator as needed.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

PYTHON="${PYTHON:-python}"
BATCH_PROFILE="$REPO_ROOT/profile/batch_profile.py"

: "${SSD_DATASET_DIR:?Set SSD_DATASET_DIR to your dataset root (or pass --data-dir to gen_batch_script.py).}"
DATA_DIR="$SSD_DATASET_DIR"
DATASETS='alpaca,gsm8k,humaneval,mt_bench,qa'
OUT_ROOT='profile/results_batch'
K=5
BATCH_SIZE=4
TOPK_SEL=5
EXP_PCT=0.2

_run() {
  local name="$1"
  shift
  echo "=== ${name} ==="
  "$PYTHON" "$BATCH_PROFILE" \
    --data-dir "$DATA_DIR" \
    --datasets "$DATASETS" \
    --output-dir "$OUT_ROOT/$name" \
    --k "$K" \
    --batch-size "$BATCH_SIZE" \
    "$@"
}

# Baseline vanila (no hispec)
_run vanila_plain --method vanila

# Vanila + hispec (intermediate rounds + target commit every 4 verifier steps)
_run vanila_hispec_interval4 --method vanila --hispec --interval 4

_run topk_expansion \
  --method topk_expansion --topk-selection $TOPK_SEL --expansion-pct $EXP_PCT

_run topk_expansion_hispec_interval4 \
  --method topk_expansion --hispec \
  --interval 4 --topk-selection $TOPK_SEL --expansion-pct $EXP_PCT

_run bump --method bump

_run morphable --method morphable

